Node 620 deactivate user
Hylozoic/hylo-node pull request #705
Opened 2021-11-16 22:24 UTC by thomasgwatson

What else does this need to work? This would be my first mutation, so curious to know if I have missed anything.

For #620

2021-11-16 22:24 UTC, thomasgwatson commented on api/graphql/index.js
> -  toggleGroupWidgetVisibility,
linter picked this up as unused, so I removed.

2021-11-17 20:02 UTC, tibetsprague requested changes

2021-11-17 20:02 UTC, tibetsprague commented on api/models/User.js
> +    await User.clearSessionsFor({sessionId, userId: this.id})
also I still think we want to delete the current session too:     req.session.destroy(), maybe that happens in the mutation?

2021-11-17 20:02 UTC, tibetsprague commented on api/models/User.js
> +    return this.set({ active: true })
I thought that .set didn't actually do a .save()? We usually do .save({ active: true })

2021-11-17 21:24 UTC, thomasgwatson commented on api/models/User.js
> +    await User.clearSessionsFor({sessionId, userId: this.id})
How do I play with the request in the graphQL context?

I only see references to `req.session` in https://github.com/Hylozoic/hylo-node/blob/d073057fe5f1a1053c1c61b517eaf1b5d634aa85/api/graphql/index.js#L371 and don't really see other mutations or queries dealing directly with the `req`. Any idea on what the convention is for this?

2021-11-17 22:06 UTC, tibetsprague commented on api/models/User.js
> +    await User.clearSessionsFor({sessionId, userId: this.id})
I dont actually... what if you actually just call logout on the front-end after the deactivate call?

2021-11-24 05:23 UTC, tibetsprague approved these changes

2021-11-24 05:23 UTC, tibetsprague commented on api/graphql/schema.graphql
> +  active: Boolean
is there ever a time we would return a deactivated me?

2021-11-24 05:37 UTC, tibetsprague requested changes

2021-11-24 05:37 UTC, tibetsprague commented on api/graphql/index.js
> +    deactivateMe: (root, { sessionId, userId }) => deactivateUser({ sessionId, userId }),
shouldnt need to pass in userId because for deactivateMe we always want to deactivate the current user

2021-11-24 05:37 UTC, tibetsprague commented on api/graphql/index.js
> +    reactivateMe: (root, { userId }) => reactivateUser({ userId }),
shouldnt need to pass in userId, always current user

2021-11-29 23:55 UTC, merged